sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging-ci

install:
  - git clone https://github.com/getredash/redash-amazon-athena-proxy.git
before_script:
  - docker-compose config
script:
  - docker-compose run --rm server create_db
  - docker-compose up -d
after_script:
  - docker-compose ps
  - docker volume ls
  - curl localhost:28080
notifications:
  slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
